###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
          - "${NGINX_PORT:-80}:80"
        restart: always
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    youtube-dl-api:
        container_name: youtube-dl-api
        depends_on:
          - nginx
        environment:
          - APP_LOCALE=en
          - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN:-semaphore://localhost%kernel.project_dir%/.env}
          - ASSETS_DIR=/opt/youtube-dl/downloads
          - SHELL_VERBOSITY=${SHELL_VERBOSITY:--1}
        image: cedrickoka/youtube-dl-api
        restart: always
